# Generated by Django 3.2.16 on 2024-01-31 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
